version: '3'
services:
    app:
        build:
            content: .
            dockerfile: ./Dockerfile
        image: composer70
        ports:
            - 8080:8080
        volumes:
            - .:/src/app
        links:
            - mysql
        environment:
            DB_HOST: mysql
            DB_DATABASE: composer70
            DB_USERNAME: app
            DB_PASSWORD: password
    mysql:
        image: mysql:5.7
        ports:
            - 13306:3306
        environment:
            MYSQL_DATABASE: composer70
            MYSQL_USER: app
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
